"""
Test Embedding DB Performance with Generated Chunks
Tests the vector database with real PDF chunks from data_processing module
"""

import json
import time
import numpy as np
from pathlib import Path
from embedding_db import EmbeddingDB


def load_chunks_from_json(json_file_path):
    """Load chunks from JSON file generated by data_processing"""
    with open(json_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Extract just the content from each chunk
    chunks = [chunk['content'] for chunk in data]
    return chunks


def get_project_root():
    """Get the project root directory"""
    return Path(__file__).parent.parent


def test_single_pdf_embedding():
    """Test embedding_db with a single PDF's chunks"""
    print("\n" + "="*70)
    print("TEST 1: Single PDF Embedding Performance")
    print("="*70)
    
    project_root = get_project_root()
    json_file = project_root / "data" / "processed" / "environment_act_chunks.json"
    
    if not json_file.exists():
        print(f"✗ JSON file not found: {json_file}")
        return None
    
    # Load chunks
    print(f"\nLoading chunks from: {json_file.name}")
    chunks = load_chunks_from_json(str(json_file))
    print(f"✓ Loaded {len(chunks)} chunks")
    
    # Initialize database
    print("\nInitializing EmbeddingDB...")
    start_time = time.time()
    db = EmbeddingDB(model_name="all-MiniLM-L6-v2")  # Faster model for testing
    init_time = time.time() - start_time
    print(f"✓ EmbeddingDB initialized in {init_time:.2f}s")
    
    # Add documents
    print(f"\nAdding {len(chunks)} chunks to database...")
    start_time = time.time()
    db.add_documents(chunks)
    add_time = time.time() - start_time
    print(f"✓ Added in {add_time:.2f}s")
    
    # Create embeddings
    print(f"\nGenerating embeddings for {len(chunks)} chunks...")
    start_time = time.time()
    db.create_embeddings()
    embedding_time = time.time() - start_time
    print(f"✓ Embeddings generated in {embedding_time:.2f}s")
    
    # Show statistics
    stats = db.get_stats()
    print(f"\nDatabase Statistics:")
    print(f"  Documents: {stats['num_documents']}")
    print(f"  Embedding dimensions: {stats['embedding_dim']}")
    print(f"  Model: {stats['model_name']}")
    
    return db, chunks, embedding_time


def test_search_queries(db, chunks):
    """Test search performance with various queries"""
    print("\n" + "="*70)
    print("TEST 2: Search Query Performance")
    print("="*70)
    
    # Sample queries about legal documents
    queries = [
        "What are the penalties for environmental violations?",
        "How are lease agreements structured?",
        "What are property rights?",
        "penalties and fines",
        "contract terms and conditions"
    ]
    
    search_times = []
    
    for i, query in enumerate(queries, 1):
        print(f"\nQuery {i}: {query}")
        
        start_time = time.time()
        results = db.search(query, top_k=3)
        search_time = time.time() - start_time
        search_times.append(search_time)
        
        print(f"  Search time: {search_time*1000:.2f}ms")
        print(f"  Top results:")
        
        for rank, (text, score) in enumerate(results, 1):
            print(f"    {rank}. Score: {score:.4f}")
            print(f"       Text: {text[:80]}...")
    
    avg_search_time = np.mean(search_times)
    print(f"\n{'─'*70}")
    print(f"Average search time: {avg_search_time*1000:.2f}ms")
    print(f"Min search time: {min(search_times)*1000:.2f}ms")
    print(f"Max search time: {max(search_times)*1000:.2f}ms")


def test_multi_pdf_embedding():
    """Test embedding_db with multiple PDFs"""
    print("\n" + "="*70)
    print("TEST 3: Multiple PDF Embedding")
    print("="*70)
    
    project_root = get_project_root()
    processed_dir = project_root / "data" / "processed"
    
    # Find all JSON files
    json_files = list(processed_dir.glob("*.json"))
    
    if not json_files:
        print(f"✗ No JSON files found in {processed_dir}")
        return None
    
    print(f"Found {len(json_files)} processed PDF files")
    
    # Initialize database
    db = EmbeddingDB(model_name="all-MiniLM-L6-v2")
    
    total_chunks = 0
    total_embedding_time = 0
    
    # Load and embed all PDFs
    for json_file in json_files:
        print(f"\nProcessing: {json_file.name}")
        
        # Load chunks
        chunks = load_chunks_from_json(str(json_file))
        num_chunks = len(chunks)
        total_chunks += num_chunks
        print(f"  Loaded {num_chunks} chunks")
        
        # Add to database
        db.add_documents(chunks)
    
    # Create embeddings for all
    print(f"\nGenerating embeddings for {total_chunks} total chunks...")
    start_time = time.time()
    db.create_embeddings()
    total_embedding_time = time.time() - start_time
    
    print(f"✓ All embeddings generated in {total_embedding_time:.2f}s")
    print(f"  Average time per chunk: {(total_embedding_time/total_chunks)*1000:.2f}ms")
    
    stats = db.get_stats()
    print(f"\nCombined Database Statistics:")
    print(f"  Total documents: {stats['num_documents']}")
    print(f"  Embedding dimensions: {stats['embedding_dim']}")
    
    # Test search
    print(f"\nTesting search on combined database...")
    test_query = "What are the legal requirements?"
    start_time = time.time()
    results = db.search(test_query, top_k=5)
    search_time = time.time() - start_time
    
    print(f"Search time: {search_time*1000:.2f}ms")
    print(f"Found {len(results)} results:")
    for i, (text, score) in enumerate(results, 1):
        print(f"  {i}. Score: {score:.4f} - {text[:70]}...")
    
    return db


def test_similarity_distribution():
    """Analyze score distribution across chunks"""
    print("\n" + "="*70)
    print("TEST 4: Similarity Score Distribution")
    print("="*70)
    
    project_root = get_project_root()
    json_file = project_root / "data" / "processed" / "environment_act_chunks.json"
    
    if not json_file.exists():
        print(f"✗ JSON file not found")
        return
    
    chunks = load_chunks_from_json(str(json_file))
    db = EmbeddingDB(model_name="all-MiniLM-L6-v2")
    db.add_documents(chunks)
    db.create_embeddings()
    
    test_query = "environmental protection penalties"
    results = db.search(test_query, top_k=len(chunks))
    
    scores = [score for _, score in results]
    
    print(f"\nAnalyzing {len(scores)} similarity scores for query:")
    print(f"'{test_query}'")
    print(f"\nScore Statistics:")
    print(f"  Highest score: {max(scores):.4f}")
    print(f"  Lowest score: {min(scores):.4f}")
    print(f"  Mean score: {np.mean(scores):.4f}")
    print(f"  Std deviation: {np.std(scores):.4f}")
    print(f"  Median score: {np.median(scores):.4f}")
    
    # Score distribution buckets
    print(f"\nScore Distribution:")
    ranges = [(0.9, 1.0), (0.7, 0.9), (0.5, 0.7), (0.3, 0.5), (0.0, 0.3)]
    for min_val, max_val in ranges:
        count = sum(1 for s in scores if min_val <= s < max_val)
        pct = (count / len(scores)) * 100
        print(f"  {min_val:.1f}-{max_val:.1f}: {count} chunks ({pct:.1f}%)")


def test_memory_usage():
    """Estimate memory usage of embeddings"""
    print("\n" + "="*70)
    print("TEST 5: Memory Usage Analysis")
    print("="*70)
    
    project_root = get_project_root()
    json_file = project_root / "data" / "processed" / "environment_act_chunks.json"
    
    if not json_file.exists():
        return
    
    chunks = load_chunks_from_json(str(json_file))
    
    # Calculate text size
    total_text_size = sum(len(chunk.encode('utf-8')) for chunk in chunks)
    print(f"\nText Data:")
    print(f"  Total chunks: {len(chunks)}")
    print(f"  Total text size: {total_text_size / 1024:.2f} KB")
    print(f"  Average chunk size: {total_text_size / len(chunks) / 1024:.2f} KB")
    
    # Create embeddings and check size
    db = EmbeddingDB(model_name="all-MiniLM-L6-v2")
    db.add_documents(chunks)
    db.create_embeddings()
    
    embedding_size = db.embeddings.nbytes
    embedding_dim = db.embeddings.shape[1]
    
    print(f"\nEmbedding Data:")
    print(f"  Embedding dimensions: {embedding_dim}")
    print(f"  Total embeddings size: {embedding_size / 1024 / 1024:.2f} MB")
    print(f"  Size per embedding: {embedding_size / len(chunks) / 1024:.2f} KB")
    
    print(f"\nMemory Ratio:")
    ratio = embedding_size / total_text_size
    print(f"  Embeddings/Text size ratio: {ratio:.2f}x")


def main():
    """Run all tests"""
    print("\n")
    print("╔" + "="*68 + "╗")
    print("║" + " "*12 + "EMBEDDING DB PERFORMANCE TEST SUITE" + " "*21 + "║")
    print("╚" + "="*68 + "╝")
    
    try:
        # Test 1: Single PDF
        result = test_single_pdf_embedding()
        if result:
            db, chunks, _ = result
            
            # Test 2: Search queries
            test_search_queries(db, chunks)
            
            # Test 4: Similarity distribution
            test_similarity_distribution()
            
            # Test 5: Memory usage
            test_memory_usage()
        
        # Test 3: Multiple PDFs
        test_multi_pdf_embedding()
        
        # Summary
        print("\n" + "="*70)
        print("✅ ALL TESTS COMPLETED SUCCESSFULLY!")
        print("="*70 + "\n")
        
    except Exception as e:
        print(f"\n❌ Test failed with error: {str(e)}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
